// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-balance.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_balance_default = defineTool({
  name: "get_balance",
  title: "Get email balance",
  description: "Return the signed-in user's prepaid email balance and any active subscription tier.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client(ctx);
    const [{ data: credits }, { data: caps }] = await Promise.all([
      sb.from("user_credits").select("balance").eq("user_id", ctx.getUserId()).maybeSingle(),
      sb.rpc("current_week_caps", { _user_id: ctx.getUserId() })
    ]);
    const tier = Array.isArray(caps) && caps[0] ? caps[0].tier : "none";
    const balance = credits?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Balance: ${balance} emails. Tier: ${tier}.` }],
      structuredContent: { balance, tier }
    };
  }
});

// src/lib/mcp/tools/list-my-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_jobs_default = defineTool2({
  name: "list_my_jobs",
  title: "List my outreach jobs",
  description: "List the signed-in user's recent Your Echo outreach jobs (agent, status, spend, created date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max jobs to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client2(ctx);
    const { data, error } = await sb.from("a2a_jobs").select("id, agent_id, status, created_at, spend_usd, emails_sent").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-referrals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_referrals_default = defineTool3({
  name: "list_my_referral_codes",
  title: "List my referral codes",
  description: "List the signed-in user's Your Echo referral codes and conversion counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client3(ctx);
    const { data, error } = await sb.from("referral_codes").select("code, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { codes: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dqovpwkmmtxqlrdvfuzz";
var mcp_default = defineMcp({
  name: "your-echo-mcp",
  title: "Your Echo",
  version: "0.1.0",
  instructions: "Query the signed-in user's Your Echo account: prepaid email balance, recent outreach jobs, and referral codes. Each tool acts as the authenticated user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_balance_default, list_my_jobs_default, list_referrals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
